spring:
  application:
    name: schedule_manager
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_manager
    username: nbc
    password: Nc@ss183790
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
